default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5


development:
  <<: *default
  database: slappe_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: slappe_test
  username: postgres
  password: postgres
  host: localhost


production:
  primary: &primary_production
    <<: *default
    database: slappe_production
    username: slappe
    password: <%= ENV["SLAPPE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: slappe_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: slappe_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: slappe_production_cable
    migrations_paths: db/cable_migrate
